# 这是一个基本的工作流程，可帮助您开始使用操作

name: WIKI-CI

# Controls when the action will run.
on:
  # 在推或拉请求事件上触发工作流，但仅针对主分支
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由可以顺序或并行运行的一个或多个作业组成
jobs:
  # 此工作流程包含一个名为“ build”的作业
  build:
    # 作业将运行的运行程序类型
    runs-on: ubuntu-latest

    # 步骤表示将作为工作一部分执行的一系列任务
    steps:
      # 在$ GITHUB_WORKSPACE下签出您的存储库，以便您的工作可以访问它
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # 使用运行程序外壳运行单个命令
      - name: 依赖环境
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'v0.81.0'
          extended: true

      - name: 构建
        run: |
          hugo --theme=pure --buildDrafts --baseUrl="https://jarick-jiao.github.io/wikibook.github.io/"

      - name: 部署
        run:  |
          cd ../public
          git config --global user.email jwqworking@outlook.com
          git config --global user.name Jarick-jiao
          git add -A
          git commit -m 'rebuilding hugo site' -a

      - name: 提交
        uses: ad-m/github-push-action@master
        with:
          github_token: 63455b5cb6325ab274db8f9c671f094a2d6fc42a
